name: Reusable workflow to execute WPT against Servo nightly.

env:
  NIGHTLY_PATH: https://download.servo.org/nightly/linux/servo-latest.tar.gz

on:
  workflow_call:
    inputs:
      layout-engine:
        required: true
        type: string
      artifact-name:
        required: true
        type: string

jobs:
  run-wpt:
    name: Run WPT suite. 
    runs-on: ubuntu-20.04
    env:
      max_chunk_id: 20
    strategy:
      matrix:
        chunk_id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
    steps:
      - name: Checkout servo repo
        uses: actions/checkout@v3
        with:
          repository: servo/servo
          path: servo
      - name: Cache libffi
        id: cache
        uses: actions/cache@v3
        with:
          path: ./libffi6_3.2.1-8_amd64.deb
          key: cache-libffi
      - name: Download libffi
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          wget http://mirrors.kernel.org/ubuntu/pool/main/libf/libffi/libffi6_3.2.1-8_amd64.deb
      - name: Prep test environment
        run: |
          python3 -m pip install --upgrade pip virtualenv
          sudo apt update
          sudo apt install -qy --no-install-recommends libgl1 libssl1.1 libdbus-1-3 libxcb-xfixes0-dev libxcb-shape0-dev libunwind8 libegl1-mesa
          sudo apt install -qy libgstreamer1.0-0 libgstreamer-gl1.0-0 libgstreamer-plugins-bad1.0-0
          sudo apt install ./libffi6_3.2.1-8_amd64.deb
      - name: Download latest nightly
        run: |
          ./mach bootstrap-gstreamer
          wget -O servo-latest.tar.gz "${{ env.NIGHTLY_PATH }}"
          tar -xzf servo-latest.tar.gz
          mkdir -p target/release
          mv servo/resources target/release/resources
          mv servo/servo target/release/servo

          SERVO_VERSION=$(./target/release/servo --version)
          echo Downloaded $SERVO_VERSION
          echo "SERVO_VERSION=$SERVO_VERSION" >> $GITHUB_ENV
        working-directory: servo
      - name: Layout argument
        if: inputs.layout-engine == '2013'
        run: |
          echo "WPT_LAYOUT_FLAG=--legacy-layout" >> $GITHUB_ENV
      - name: Run tests
        run: |
          python3 ./mach test-wpt \
            --release ${WPT_LAYOUT_FLAG} \
            --log-wptreport=wpt-report-${{ matrix.chunk_id }}.json \
            --processes $(nproc) --timeout-multiplier 2 \
            --always-succeed \
            --browser-version "$SERVO_VERSION" \
            --this-chunk ${{ matrix.chunk_id }} \
            --total-chunks ${{ env.max_chunk_id }}
        working-directory: servo
      - name: Archive the wpt result chunk
        uses: actions/upload-artifact@v3
        with:
          name: ${{ inputs.artifact-name }} 
          path: servo/wpt-report-${{ matrix.chunk_id }}.json

